language: en

pipeline: 
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
    "pooling": "mean"
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: true
    model_confidence: "linear_norm"
  
  

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    random_seed: 42
    constrain_similarities: true
  - name: RulePolicy